### ISSUE TITLE
Music - Artists (and all varations) missing

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.widgets#1]
Now, not sure if this is a helper script issue or the new widget part of the helper script but I noticed in the latest beta (krypton) that I can't choose any music widgets of the class "artist" - I find song, album, etc but nothing artist related.  I used to have a widget "random artists" but noticed a log error that it was no longer found. So I tried to add it again only to find no widgets for artists available.

```
19:34:54.038 T:14884   ERROR: Error loading Smart playlist special://skin/extras/widgetplaylists/randomartists.xsp (failed to read file)
19:34:54.038 T:14884   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://skin/extras/widgetplaylists/randomartists.xsp
```

I know the error above is due to the re-write and the file moved but that's what lead me to this issue.

Oh and also - if you define a splash screen in the skin things don't seem to work.  

noticed the runscript used to call "spashscreen" but it looks like it was renamed to "show_splash" but changing that in the startup.xml still did not work so I am thinking there is another issue - I am so novice with python I figured it would be easy for you to find/fix instead of me spending an hour struggling to find the most likely obvious issue hehe

**Comment by marcelveldt** [comment]
Oops, I indeed forgot the artist widgets. Can you remember which widgets existed ? Only random artists or where there some more ?

I'll take a look at the show splash method, didn't test that one tbh

**Comment by marcelveldt** [comment]
I will post new beta versions in a few minutes. Can you test if it's fixed with that ?

**Comment by mgonzales71** [comment]
Yea I see the Artist Widgets now, I think you got the widget variations that were available in the skin before already,

The splash screen / video option displays OK but after the (i think 5 seconds) never hands off to display home.xml unless you press backspace, esc, etc.

don't see any errors though.

oh btw - since you moved all the skin issue, etc to trello - I couldn't find out how to make new cards, etc

do I need to join a group or something?

I think my ID on there is @mgonzales71 

I am in the process of creating a new busy spinner resource addon for krypton using the animated png files. did a test and they work.

I also am creating 2 weather icon sets (color and white/mono) and a new sound resource for the skin

I will create new repos and then if you like them you can fork and add them to your repo once done.

**Comment by mgonzales71** [comment]
with latest updates looks like show_startup is fixed now
