### ISSUE TITLE
path as filter does not allow forward slashes

### ISSUE THREAD

**Issue by Infray** [marcelveldt/script.skin.helper.widgets#12]
Hi Marcel

I'm currently using a feature added in following [merge](https://github.com/marcelveldt/script.skin.helper.widgets/pull/7) to filter a list of episodes by path.
e.g. `plugin://script.skin.helper.widgets/?action=recent&path=m:\series&mediatype=episodes&reload=$INFO[Window(Home).Property(widgetreload-episodes)]']`

However by the time the api is called the path filter has been transformed to `m:/series` and doesn't match my setup anymore.

Any reason why this is happening?

I'm running following setup:
Kodi v18 alpha1 on Windows 10
EstuaryModV2 2.3.1
script.skin.helper.widgets 1.0.28

Kind Regards
Laurens

**Comment by marcelveldt** [comment]
Did you try to put the path inside quotes ?

**Comment by redglory** [comment]
I use path with nfs://192.168.1.77/tvshows/ without any issue. 

Try putting "\" at the end of your path.

Can you provide a log?
