### ISSUE TITLE
Filter recommended items on genre?

### ISSUE THREAD

**Issue by jingai** [marcelveldt/script.skin.helper.widgets#16]
Over at [Kodi-Alexa](https://github.com/m0ngr31/kodi-alexa) we make use of this script to provide recommended items to the user.

We currently support inquiries that include specified genres as well, like:

```
Alexa, ask Kodi to play a random Comedy movie
Alexa, ask Kodi what new Family movies do we have?
Alexa, ask Kodi to watch a random Sci-Fi tv show
```

[We'd like to extend this to inquiries for recommended items as well](https://github.com/m0ngr31/kodi-alexa/issues/193), which would mean adding a tag like:

`plugin://script.skin.helper.widgets/?action=recommended&mediatype=movies&genre=Comedy`

Would it be feasible to add a new `genre` tag to `recommended` for music, artists, albums, songs, music videos, movies, and shows?

If you can provide a little guidance on how you think this should go, I don't mind doing the work to implement it.  We'd rather extend your script than duplicate effort, if possible.

**Comment by jingai** [comment]
I've added the `genre` option and it seems to work OK.  Would you accept a PR against 1.0.22 (Krypton release version) though?

**Comment by marcelveldt** [comment]
PR's are always welcome !

**Comment by jingai** [comment]
Is there any chance we'd see a new Krypton release though?

**Comment by marcelveldt** [comment]
yes, I'm planning so

**Comment by jingai** [comment]
Thanks for your responses.  We decided ultimately to go in another direction, so we won't personally be needing this addition.

But if you think there might be another use for it, feel free to leave the Issue open and I'll make a PR when I get a chance.  Otherwise, you're welcome to close it.
