### ISSUE TITLE
invalid content type

### ISSUE THREAD

**Issue by jeroenpardon** [marcelveldt/script.skin.helper.widgets#17]
Is it really necessary to set _Container.Content_ to _favourites_ in the favourites nodes?

_Favourites_ is not a valid content type and it messes up conditions I have in place.

**Comment by marcelveldt** [comment]
well, I can just set it to files or something. Point is that you should consider to not use container.content to determine the content type. Better to use listitem.dbtype instead.

**Comment by jeroenpardon** [comment]
Well, that isn't exactly true and dependant on the situation / location. For viewtype selection for example container.content is advised. Apart from that dbtype can't be used everywhere (yet) and has many practical issues.

**Comment by marcelveldt** [comment]
OK, I will set the content type for the favourites widget to "files". To determine what content is in the favourites widget you should use ListItem.DBTYPE if you want.

**Comment by jeroenpardon** [comment]
Thanks. I will, the problems I am referring to only pose a problem when using the paths in library windows.

**Comment by marcelveldt** [comment]
I'll check in the change later today

**Comment by jeroenpardon** [comment]
No rush, cheers

**Comment by jeroenpardon** [comment]
btw, my request also applies to the other custom content types that are being used in the various nodes like media and pvr
