### ISSUE TITLE
cannot import name TheTvDb

### ISSUE THREAD

**Issue by hobbypunk90** [marcelveldt/script.skin.helper.widgets#3]
Hello,
<br />
<br />i got the nearly the same error like [this](https://github.com/marcelveldt/script.skin.helper.service/issues/73) :
<br />
<br />```
<br />21:49:36.514 T:1306522512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
<br />                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
<br />                                            Error Type: <type 'exceptions.ImportError'>
<br />                                            Error Contents: cannot import name TheTvDb
<br />                                            Traceback (most recent call last):
<br />                                              File "/home/kodi/.kodi/addons/script.skin.helper.widgets/plugin.py", line 9, in <module>
<br />                                                import main
<br />                                              File "/home/kodi/.kodi/addons/script.skin.helper.widgets/resources/lib/main.py", line 18, in <module>
<br />                                                from artutils import ArtUtils, process_method_on_list
<br />                                              File "/home/kodi/.kodi/addons/script.module.skin.helper.artutils/lib/artutils.py", line 28, in <module>
<br />                                                from thetvdb import TheTvDb
<br />                                            ImportError: cannot import name TheTvDb
<br />                                            -->End of Python script error report<--
<br />21:49:36.717 T:1948012800   ERROR: GetDirectory - Error getting plugin://script.skin.helper.widgets/
<br />21:49:36.718 T:1948012800   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.skin.helper.widgets/) failed
<br />```
<br />
<br />
<br />Greets,
<br />Marcel

**Comment by mgonzales71** [comment]
Not the expert here but you may want to try installing Marcel's repo (beta code fyi):

https://github.com/marcelveldt/repository.marcelveldt/blob/master/repository.marcelveldt/repository.marcelveldt-1.0.1.zip

and then making sure you have the latest of all the modules installed which includes script.module.thetvdb

latest at time of this reply is but install (or even reinstall) from repo or zip:
https://github.com/marcelveldt/repository.marcelveldt/blob/master/script.module.thetvdb/script.module.thetvdb-1.0.10.zip

"thetvdb" is defined in this add on module.

Hope this helps - I had some strange errors issues and what eventually solved it for me was to re-install the helper script and all the modules and then restart kodi.

fingers crossed :)

**Comment by hobbypunk90** [comment]
This helped, thanks 🙂

**Comment by mgonzales71** [comment]
Glad to hear that!

Cheers and Happy Holidays!

Mario

**Comment by mgonzales71** [comment]
Marcel - you can close this issue and https://github.com/marcelveldt/script.skin.helper.service/issues/73
