### ISSUE TITLE
Kodi 19 compatibility - Python 3 migration

### ISSUE THREAD

**Issue by bernd-wechner** [marcelveldt/script.skin.helper.widgets#42]
The time is coming. As far as I can tell although Kodi 19 has no firm release date, it's stable enough for daily use, and it marks the transition to Python 3, with Python to at end of life this year.

To wit, it would useful to upgrade this addon to Python 3 and produce a Kodi 19 compatible version.

**Comment by Angelinas1** [comment]
New version is public
