### ISSUE TITLE
New episodes not working properly, maybe?

### ISSUE THREAD

**Issue by sjp15991** [marcelveldt/script.skin.helper.widgets#43]
Hey

I downloaded this through the add_ons section on Kodi (not here directly on github). I love it, thanks so much! I just have one problem, but I might be being stupid. I was using it perfectly fine and it was showing under next episodes the episode after the one I had most recently watched even though I had not watched the first season on Kodi (pls say if this is unclear) but then I cleared my library completely, cleaned it and reupdated it but it now seems like it no longer works the way before. If for example you start watching season 2 of a tv shows and you finish episode 1, before it would season 2 episode 2 under next episode (or I think maybe its called 'new episode') now instead it tells me that the next episode is in fact season 1 episode 1. Obviously I can mark all episodes before my point as watched (and did do that in the end) but it doesnt work very well for a lot of shows, where I might dip in and out. This could also just be the way it is supposed to work but I remember pretty clearly it working the other way before. Any help would be greatly appreciated! Thanks again for this basically essential add on.

I should note also that I am using Kody Leia 19

**Comment by Angelinas1** [comment]
New version is now for Matrix, please use that
