### ISSUE TITLE
Adjust PVR info shown in the fullscreen widget

### ISSUE THREAD

**Issue by kalle2000** [marcelveldt/script.skin.helper.widgets#44]
I am using a PVR and configured the home screen to show a widget with TV channel group on the home screen (Additional Widgets --> Skin Helper Service Widgets --> PVR --> TV channels: <group>). As I am using pvr artwork this looks really nice, however there is some info I am missing.

This is how it looks for my Shows library: [Screenshot](https://ibb.co/HC4crfM)
Below the show name, there is additional info (like year, MPAA rating and watched progress for shows / duration, end time for movies). For PVR some internal info is shown (Systemname of Kodi and version of the skin in use).

Can you adjust that row to show: Name of the PVR Channel, Year and start/end time? Basically same information as shown in the programme information screen. By the way, on the full screen widget the button "more information" does not work (I expected it fwd to programme information).

Thank you so much.

**Comment by Angelinas1** [comment]
Shw only provide info, skin is tool for view...
See in skin thread this isn't isue for this script

**Comment by kalle2000** [comment]
Can you explain what your answer means? I dont understand? Is this an issue of the respective Kodi skin I am using? The skin creater told me its missing information which is passed to the skin.

**Comment by Angelinas1** [comment]
What skin you use ?
Look like skin.arctic.horizon...see image from link
That button doesen't work for me in that skin
[img]https://i.imgur.com/PhH002G.png[/img]
Same tvchanel, same widget mine skin
working all exept DialogInfo, like on your image "more info"
[img]https://i.imgur.com/WhQhCsu.png[/img]

**Comment by Angelinas1** [comment]
That skin doesent have support for pvr from metadatautils,I amfreid this info cant work in that skin.
This widget working well but need full support of shs.
Edit:
Working-Skin have support for SHS :
Skin Shows art in Live TV Channel, that mean.....missing properties in home.xml for SkinHelper for info
[img]https://i.imgur.com/Uwx4YCs.png[/img]
