### ISSUE TITLE
Time in Next Airing Episodes widget read as 08/06/1905

### ISSUE THREAD

**Issue by wishx** [marcelveldt/script.skin.helper.widgets#5]
Time in Next Airing Episodes widget read as 08/06/1905. I am using Kodi 17 and Arctic Zephyr skin. I also had the Skin Helper Widget doing a Recently Added Episodes widget and the same issue occurred. If you navigate to the right through the posters of shows, the date increased by one day (or however many it should), but the date was still in 1905.

It seems to work correctly in SPMC 16.5.5 Kodi Jarvis.

If you need more information, please let me know.

Thank you.
Derek

**Comment by marcelveldt** [comment]
This is already on my radar. Somehow on Krypton only the dates get all messed up while they're fine in Jarvis. I'll fix it asap

**Comment by mtbooker** [comment]
I am uncertain if this is related, but the panel labels on the Next Aired widget in Aeon Nox Silvo now only show the episode number and title, but no air date.  Is this information still provided by skinhelper? I'm trying to figure out how we can bring it back. Thanks!

**Comment by wishx** [comment]
Now it's coming up as the proper day and month, but 0 as the year like 03/26/0 for today's date. 
Skin Helper Service Widgets v1.0.26 on Kodi 17.1.

**Comment by popycok** [comment]
Is there a fix for this for spmc krypton 17.4? I have been a fan of titan for a while now I have updated to spmc for the search and recommendations on android tv until kodi 18 and a titan is released for it that is a official release. Everything works great on spmc with titan krypton except the next episodes show 1905-1906 dates

**Comment by popycok** [comment]
I have installed your beta repo and updated all skin service updates

**Comment by marcelveldt** [comment]
ok thanks for reminding me. I've been sick for a while and now catching up with all reports and requests. Will take a look at this asap

**Comment by popycok** [comment]
You kick ass!, I heard you were sick is it serious? I hope you feel better and it doesn't stay too long just want to say again that I love Titan it is the only skin I use

**Comment by marcelveldt** [comment]
sorry for the late reply. issue should be fixed by now.
