### ISSUE TITLE
[request] Auto refresh content providers in library windows

### ISSUE THREAD

**Issue by jeroenpardon** [marcelveldt/script.skin.helper.widgets#9]
Hi Marcel,

Apart from widgets I use the script provided content paths in library views. Recommended episodes for example is a great way to catch up on all my shows. The only shortcoming here is that there is no auto refresh when used in the library. I have to exit the window and re-enter for it to update.

Is there any way you can make auto refresh possible in library views too?

[This script](https://github.com/jeroenpardon/script.watchlist) Bob wrote for me at the time did just that but I guess some changes in Kodi made the auto refresh stop working there too. I have been looking at trying to fix that myself but it is beyond my expertise at the moment I'm afraid. 

Cheers,
Jeroen

**Comment by marcelveldt** [comment]
Doesn't appending the Window property work correctly ?

plugin://fullpluginpath/?refresh=$INFO[Window(Home).Property(widgetsreload2)]

That should refresh it every 5 minutes
